### ISSUE TITLE
Algoritmo

### ISSUE THREAD

**Issue by fabiofumarola** [Gigitsu/thesis#4]
Spendi meno tempo sul resto ma concentrati su:
1. Spiegare l'architettura della rete, evidenziando la sotto-architettura della cella e la funzione di attivazione (porre enfasi sulle scelte di implementazione, puoi citare lua perche?, GPU perche' con vantaggi e svantaggi)
2. parlare delle trasformazioni sull'input
3. parlare del layer finale per fare la presizione SOFT MAX

**Comment by Gigitsu** [comment]
:D
